export const config = Object.freeze({
  samplePath: "./data/sample.json",
  pdfWorkerPath: "./vendor/pdfjs/pdf.worker.min.mjs",
  pdfCMapPath: "./vendor/pdfjs/cmaps/",
  pdfStandardFontPath: "./vendor/pdfjs/standard_fonts/",
  pdfWasmPath: "./vendor/pdfjs/wasm/",
  sampleLoadDelayMs: 650,
  maxExcerptLength: 280,
  maxSlidePages: 80,
  maxTextbookPages: 120,
  maxFileSizeMb: 60,
  maxMatchesPerSlide: 4,
  maxExercisesPerSlide: 4,
  pdfRenderScale: 1.35,
  pdfImageQuality: 0.82,
  lineMergeTolerance: 3,
  paragraphGapMultiplier: 1.75,
  minimumMatchScore: 0.08,
  minimumExerciseScore: 0.04,
  highConfidenceScore: 0.32,
  mediumConfidenceScore: 0.17,
  maxKeyConcepts: 6,
  stopWords: Object.freeze([
    "about", "after", "again", "also", "among", "because", "before", "being",
    "between", "both", "could", "does", "each", "from", "have", "into", "more",
    "most", "other", "over", "same", "such", "than", "that", "their", "there",
    "these", "they", "this", "those", "through", "under", "very", "what", "when",
    "where", "which", "while", "with", "would", "your", "the", "and", "for", "are",
    "but", "not", "you", "all", "any", "can", "has", "how", "its", "our", "was",
    "will", "page", "chapter", "figure", "example", "course", "lecture", "slide",
    "econ", "principles"
  ]),
  confidenceLevels: ["low", "medium", "high"],
  features: Object.freeze({
    pdfAnalysis: true,
    webPractice: false,
  }),
});
